import { ICompany } from "./interfaces/company";

export const companyList: ICompany[] = [
  {
    id: "autoGeneratedTextId1",
    companyName: "AVA Company",
    email: "ava@test.com",
    phoneNumber: "+909090909090",
    createdAt: "2020-02-26T15:20:48.517Z"
  },
  {
    id: "autoGeneratedTextId2",
    companyName: "XiX Company",
    email: "xix@test.com",
    phoneNumber: "+272727272727",
    createdAt: "2018-08-26T15:30:48.517Z"
  },
  {
    id: "autoGeneratedTextId3",
    companyName: "VWV Company",
    email: "vwv@test.com",
    phoneNumber: "+696969696969",
    createdAt: "2016-03-26T15:10:48.517Z"
  },
  {
    id: "autoGeneratedTextId4",
    companyName: "XYZ Company",
    email: "xyz@test.com",
    phoneNumber: "+112211221122",
    createdAt: "2020-02-26T15:20:48.517Z"
  },
  {
    id: "autoGeneratedTextId5",
    companyName: "OPQ Company",
    email: "opq@test.com",
    phoneNumber: "+343434343434",
    createdAt: "2018-08-26T15:30:48.517Z"
  },
  {
    id: "autoGeneratedTextId6",
    companyName: "ABC Company",
    email: "zbc@test.com",
    phoneNumber: "+090909090909",
    createdAt: "2016-03-26T15:10:48.517Z"
  },
  {
    id: "autoGeneratedTextId7",
    companyName: "Lola Company",
    email: "lola@test.com",
    phoneNumber: "+909090909090",
    createdAt: "2020-02-26T15:20:48.517Z"
  },
  {
    id: "autoGeneratedTextId8",
    companyName: "Coco Company",
    email: "coco@test.com",
    phoneNumber: "+272727272727",
    createdAt: "2018-08-26T15:30:48.517Z"
  },
  {
    id: "autoGeneratedTextId9",
    companyName: "W2E Company",
    email: "w2e@test.com",
    phoneNumber: "+696969696969",
    createdAt: "2016-03-26T15:10:48.517Z"
  },
  {
    id: "autoGeneratedTextId10",
    companyName: "Roar Company",
    email: "roar@test.com",
    phoneNumber: "+112211221122",
    createdAt: "2020-02-26T15:20:48.517Z"
  },
  {
    id: "autoGeneratedTextId11",
    companyName: "Riki Company",
    email: "riki@test.com",
    phoneNumber: "+343434343434",
    createdAt: "2018-08-26T15:30:48.517Z"
  },
  {
    id: "autoGeneratedTextId12",
    companyName: "Volla Company",
    email: "volla@test.com",
    phoneNumber: "+090909090909",
    createdAt: "2016-03-26T15:10:48.517Z"
  },
]