import { Injectable } from "@angular/core";
import { BehaviorSubject, Observable, of } from "rxjs";
import { delay, tap } from "rxjs/operators";

import { companyList } from "../company.db";
import { ICompany, DtoCreateCompany, Company } from "../interfaces/company";

@Injectable({ providedIn: 'root' })
export class CompanyService {
  constructor() { }

  private _companyList = new BehaviorSubject<ICompany[]>(companyList);
  private _isLoading = new BehaviorSubject(false);
  private _currentIdPostfix = 12;

  get isLoading$() {
    return this._isLoading.asObservable();
  }

  getCompanies(): Observable<ICompany[]> {
    this._isLoading.next(true);
    return this._companyList.asObservable().pipe(
      delay(1000),
      tap(_ => this._isLoading.next(false))
    );
  }

  addCompany(dto: DtoCreateCompany): Observable<any> {
    this._isLoading.next(true);
    const newCompany = new Company({
      id: `autoGeneratedTextId${++this._currentIdPostfix}`,
      companyName: dto.companyName,
      email: dto.email,
      phoneNumber: dto.phoneNumber,
      createdAt: new Date().toISOString()
    });
    const updated = [...this._companyList.value, newCompany.value];
    this._companyList.next(updated);
    return of({
      status: 200,
      message: "Company created successfully!"
    }).pipe(delay(1000), tap(_ => this._isLoading.next(false)));
  }

  deleteCompany(companyId: string): Observable<any> {
    this._isLoading.next(true);
    const updated = this._companyList.value.filter(company => company.id !== companyId);
    this._companyList.next(updated);
    return of({
      status: 200,
      message: "Company deleted successfully!"
    }).pipe(delay(1000), tap(_ => this._isLoading.next(false)))
  }

  getDesignations(): Observable<Array<{ key: number, label: string }>> {
    return of([
      { key: 1, label: 'Developer' },
      { key: 2, label: 'Manager' },
      { key: 3, label: 'System Admin' },
      { key: 4, label: 'Team Lead' },
      { key: 5, label: 'PM' }
    ])
  }

  getSkills(): Observable<string[]> {
    return of([
      'Java', 'Angular', 'CSS', 'HTML', 'JavaScript', 'UI', 'SQL', 'React', 'PHP',
      'GIT', 'AWS', 'Python', 'Django', 'C', 'C++', 'C#', 'Unity', 'R', 'AI',
      'NLP', 'Photoshop', 'Nodejs'
    ])
  }
}